export const itemsData = [
    {
      id: 1,
      image: '/src/assets/images/image-waffle-desktop.jpg',
      icon: '/src/assets/images/icon-add-to-cart.svg',
      add: 'Add to Cart',
      name: 'Waffle',
      description: 'Waffle with Berries',
      price: '$6.50',
    },
    {
        id: 2,
        image: '/src/assets/images/image-creme-brulee-desktop.jpg',
        icon: '/src/assets/images/icon-add-to-cart.svg',
        add: 'Add to Cart',
        name: 'Crème Brûlée',
        description: 'Vanilla Bean Crème Brûlée',
        price: '$7.00',
    },
    {
        id: 3,
        image: '/src/assets/images/image-macaron-desktop.jpg',
        icon: '/src/assets/images/icon-add-to-cart.svg',
        add: 'Add to Cart',
        name: 'Macaron',
        description: 'Macaron Mix of Five',
        price: '$8.00',
    },
    {
        id: 4,
        image: '/src/assets/images/image-tiramisu-desktop.jpg',
        icon: '/src/assets/images/icon-add-to-cart.svg',
        add: 'Add to Cart',
        name: 'Tiramisu',
        description: 'Classic Tiramisu',
        price: '$5.50',
    },
    {
        id: 5,
        image: '/src/assets/images/image-baklava-desktop.jpg',
        icon: '/src/assets/images/icon-add-to-cart.svg',
        add: 'Add to Cart',
        name: 'Baklava',
        description: 'Pistachio Baklava',
        price: '$4.00',
    },
    {
        id: 6,
        image: '/src/assets/images/image-meringue-desktop.jpg',
        icon: '/src/assets/images/icon-add-to-cart.svg',
        add: 'Add to Cart',
        name: 'Pie',
        description: 'Lemon Meringue Pie',
        price: '$5.00',
    },
    {
        id: 7,
        image: '/src/assets/images/image-cake-desktop.jpg',
        icon: '/src/assets/images/icon-add-to-cart.svg',
        add: 'Add to Cart',
        name: 'Cake',
        description: 'Red Velvet Cake',
        price: '$4.50',
    },
    {
        id: 8,
        image: '/src/assets/images/image-brownie-desktop.jpg',
        icon: '/src/assets/images/icon-add-to-cart.svg',
        add: 'Add to Cart',
        name: 'Brownie',
        description: 'Salted Caramel Brownie',
        price: '$4.50',
    },
    {
        id: 9,
        image: '/src/assets/images/image-panna-cotta-desktop.jpg',
        icon: '/src/assets/images/icon-add-to-cart.svg',
        add: 'Add to Cart',
        name: 'Panna Cotta',
        description: 'Vanilla Panna Cotta',
        price: '$6.50',
    },
];